insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo, id, detalhes) values (0, false, 'RAFAEL', now(), '"org.h2.engine.Session.prepareCommand(Session.java:595) ~[h2-1.4.200.jar:1.4.200]"', 100, 0, '10.01.2', 'erro 1', 1,'ocorreu de madrugada')
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo, id, detalhes) values (2, false, 'OSEIAS', now(), '"java.lang.IllegalArgumentException: Invalid path: /storage/emulated/0 Caused by: android.system.ErrnoException: statvfs failed: EACCES (Permission denied)'', 100, 0, ''10.01.2'', ''android.system.ErrnoException: statvfs failed: EACCES (Permission denied)"', 100, 1, '10.01.4', 'erro 2', 2,'ocorreu pela manhã')
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo, id, detalhes) values (1, false, 'WESLEY', now(), '"Caused by: android.system.ErrnoException: statvfs failed: EACCES (Permission denied) at libcore.io.Linux.statvfs(Native Method) at libcore.io.BlockGuardOs.statvfs(BlockGuardOs.java:330)"', 100, 2, '10.01.8', 'erro 3', 3,'ocorreu por 20 min')
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo, id, detalhes) values (0, false, 'RENATA', now(), '"at dalvik.system.VMRuntime.newNonMovableArray(Native Method)"', 100, 1, '10.01.9', 'erro 4', 4,'ocorreu ao inserir novo usuário')
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo, id, detalhes) values (0, false, 'RAFAEL', now(), '"com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)"', 100, 0, '10.01.1', 'erro 5', 5,'ocorreu após diversas requisições')
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), '"at java.lang.Thread.nativeCreate(Native Method) at java.lang.Thread.start(Thread.java:1063)"',100, 1, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), '"java.lang.IllegalArgumentException: View=DecorView@72960a9[] not attached to window manager at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:473)"',101, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (1, false, 'FULANO', now(), '"at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java"',102, 1, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), '"teste"',103, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (1, false, 'FULANO', now(), '"teste"',104, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), '"teste"',105, 1, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (1, false, 'FULANO', now(), 'teste',106, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',107, 1, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (1, false, 'FULANO', now(), 'teste',108, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',109, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',110, 1, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (1, false, 'FULANO', now(), 'teste',111, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',112, 2, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',113, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (1, false, 'FULANO', now(), 'teste',114, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (2, false, 'FULANO', now(), 'teste',115, 2, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',116, 1, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (1, false, 'FULANO', now(), 'teste',117, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',118, 2, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',119, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (1, false, 'FULANO', now(), 'teste',120, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',121, 1, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',122, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (1, false, 'FULANO', now(), 'teste',123, 2, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (2, false, 'FULANO', now(), 'teste',124, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',125, 1, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',126, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (1, false, 'FULANO', now(), 'teste',127, 2, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (2, false, 'FULANO', now(), 'teste',128, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',129, 1, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',130, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (1, false, 'FULANO', now(), 'teste',131, 2, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',132, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (2, false, 'FULANO', now(), 'teste',133, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (1, false, 'FULANO', now(), 'teste',134, 1, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',135, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (1, false, 'FULANO', now(), 'teste',136, 2, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (1, false, 'FULANO', now(), 'teste',137, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',138, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (2, false, 'FULANO', now(), 'teste',139, 2, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',140, 1, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (1, false, 'FULANO', now(), 'teste',141, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',142, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (1, false, 'FULANO', now(), 'teste',143, 2, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (0, false, 'FULANO', now(), 'teste',144, 0, '10.01.2', 'teste', 'aaa');
insert into erro (ambiente, arquivado, coletor, data_hora, descricao, eventos, level, origem, titulo,  detalhes) values (2, false, 'FULANO', now(), 'teste',145, 1, '10.01.2', 'teste', 'aaa');

insert into usuario(nome, email, senha, token) values ('teste', 'teste@test.com', '$2a$10$RCY3VHJbXq12w4evcO9TEuYfBsC.aAyaYTJ1M2LEKSghp.oGlBsnu', 'bXq12w4evcO9TEuYfBsC');
